# Webpack Configuration
[webpack]
files = [
    "webpack.base.conf.js",
    "webpack.common.js",
    "webpack.config.babel.js",
    "webpack.config.base.js",
    "webpack.config.common.js",
    "webpack.config.dev.js",
    "webpack.config.development.js",
    "webpack.config.images.js",
    "webpack.config.js",
    "webpack.config.prod.js",
    "webpack.config.production.js",
    "webpack.config.staging.js",
    "webpack.config.test.js",
    "webpack.dev.js",
    "webpack.main.config.js",
    "webpack.mix.js",
    "webpack.plugins.js",
    "webpack.prod.js",
    "webpack.renderer.config.js",
    "webpack.rules.js",
    "webpack.test.conf.js",
]
