"4GL" = "informix"
"Haxe AST dump" = "haxe"
"asp (html)" = "asp"
"azure-pipelines" = "azurepipelines"
"c-al" = "c_al"
"cmake-cache" = "cmake"
"code-referencing" = "vscode"
"code-text-binary" = "binary"
"cuda-cpp" = "nvidia"
"django-html" = "django"
"django-txt" = "django"
"dylan-lid" = "dylan"
"fortran-modern" = "fortran"
"fortran_fixed-form" = "fortran"
"git-commit" = "git"
"git-rebase" = "git"
"gml-gm81" = "gamemaker81"
"gml-gms" = "gamemaker"
"gml-gms2" = "gamemaker2"
"home-assistant" = "homeassistant"
"html-eex" = "eex"
"hunspell.aff" = "hunspell"
"hunspell.dic" = "hunspell"
"json-tmlanguage" = "json"
"lang-cfml" = "cf"
"laravel-blade" = "blade"
"literate haskell" = "haskell"
"manifest-yaml" = "cloudfoundry"
"objective-c" = "c"
"objective-cpp" = "cpp"
"phoenix-heex" = "eex"
"pip-requirements" = "python"
"platformio-debug.asm" = "platformio"
"platformio-debug.disassembly" = "platformio"
"platformio-debug.memoryview" = "platformio"
"search-result" = "vscode"
"source.css.styled" = "styled"
"stencil-html" = "stencil"
"systemd-unit-file" = "systemd"
"vue-directives" = "vue"
"vue-injection-markdown" = "vue"
"vue-interpolations" = "vue"
"vue-sfc-style-variable-injection" = "vue"
"yaml-tmlanguage" = "yaml"
FortranFreeForm = "fortran"
SAS = "sas"
Swagger = "swagger"
abl = "progress"
actionscript = "actionscript"
ada = "ada"
advpl = "advpl"
affectscript = "affectscript"
ahk = "autohotkey"
al = "al"
ansible = "ansible"
antlr = "antlr"
anyscript = "anyscript"
apacheconf = "apache"
apex = "apex"
apiblueprint = "apib"
apl = "apl"
applescript = "applescript"
arm = "assembly"
asciidoc = "asciidoc"
asm = "assembly"
asp = "asp"
aspnetcorerazor = "razor"
ats = "ats"
autoit = "autoit"
avro = "avro"
azcli = "azure"
ballerina = "ballerina"
bat = "bat"
bats = "bats"
bazel = "bazel"
befunge = "befunge"
befunge98 = "befunge"
bibtex = "latex"
biml = "biml"
blade = "blade"
bolt = "bolt"
bosque = "bosque"
bridlensis = "nsi"
c = "c"
cabal = "cabal"
caddyfile = "caddy"
cddl = "cddl"
ceylon = "ceylon"
cfc = "cfc"
cfmhtml = "cfm"
cfml = "cf"
clojure = "clojure"
clojurescript = "clojurescript"
cmake = "cmake"
cobol = "cobol"
coffeescript = "coffeescript"
confluence = "confluence"
cookbook = "chef_cookbook"
cpp = "cpp"
crystal = "crystal"
csharp = "csharp"
css = "css"
cuda = "cuda"
cython = "cython"
d = "dlang"
dal = "dal"
dart = "dartlang"
declarative = "jenkins"
diet = "dlang"
diff = "diff"
dml = "dlang"
dockercompose = "docker"
dockerfile = "docker"
doctex = "tex"
dot = "graphviz"
dotenv = "config"
dotjs = "dotjs"
doxygen = "doxygen"
drools = "drools"
dscript = "dlang"
dustjs = "dustjs"
dylan = "dylan"
edge = "edge"
eex = "eex"
elixir = "elixir"
elm = "elm"
erb = "erb"
erlang = "erlang"
es = "elastic"
eskip = "skipper"
falcon = "falcon"
feature = "cucumber"
fortran = "fortran"
fsharp = "fsharp"
fthtml = "fthtml"
ftl = "freemarker"
galen = "galen"
gcode = "gcode"
gdscript = "godot"
genstat = "genstat"
glsl = "glsl"
glyphs = "glyphs"
gnuplot = "gnuplot"
go = "go"
graphql = "graphql"
groovy = "groovy"
haml = "haml"
handlebars = "handlebars"
happenings = "pddl_happenings"
harbour = "harbour"
haskell = "haskell"
haxe = "haxe"
helm = "helm"
hjson = "hjson"
hlsl = "opengl"
hosts = "host"
html = "html"
http = "http"
hxml = "haxe"
hy = "hy"
icl = "icl"
ignore = "docker"
imba = "imba"
ini = "conf"
ink = "ink"
innosetup = "innosetup"
io = "io"
iodine = "iodine"
jade = "pug"
janet = "janet"
java = "java"
javascript = "js"
javascriptreact = "reactjs"
jekyll = "jekyll"
jenkins = "jenkins"
jenkinsfile = "jenkins"
jinja = "jinja"
json = "json"
json5 = "json5"
jsonc = "json"
jsonl = "json"
jsonnet = "jsonnet"
julia = "julia"
juliamarkdown = "julia"
kivy = "kivy"
kos = "kos"
kotlin = "kotlin"
kusto = "kusto"
latex = "latex"
latino = "latino"
less = "less"
lex = "lex"
lisp = "lisp"
log = "log"
lolcode = "lolcode"
lsl = "lsl"
lua = "lua"
makefile = "makefile"
markdown = "markdown"
marko = "marko"
matlab = "matlab"
maxscript = "maxscript"
mdx = "markdownx"
mediawiki = "mediawiki"
mel = "maya"
menhir = "ocaml"
meson = "meson"
mjml = "mjml"
mlang = "mlang"
mojolicious = "mojolicious"
mongo = "mongo"
mson = "mson"
nearley = "nearly"
nfl = "nsi"
nim = "nim"
nimble = "nimble"
nix = "nix"
nsis = "nsi"
nsl = "nsi"
nunjucks = "nunjucks"
objectpascal = "delphi"
ocaml = "ocaml"
ocamllex = "ocaml"
openhab = "openHAB"
oracle = "plsql"
pascal = "delphi"
pddl = "pddl"
pde = "processinglang"
perl = "perl"
perl6 = "perl6"
pgsql = "pgsql"
php = "php"
pine = "pine"
pinescript = "pine"
plaintext = "text"
plan = "pddl_plan"
plsql = "plsql"
polymer = "polymer"
pony = "pony"
postcss = "postcss"
powerquerymlanguage = "mlang"
powershell = "powershell"
prisma = "prisma"
prolog = "prolog"
prometheus = "prometheus"
properties = "properties"
proto = "protobuf"
proto3 = "protobuf"
pug = "pug"
puppet = "puppet"
purescript = "purescript"
pyret = "pyret"
python = "python"
qlik = "qlikview"
qml = "qml"
qsharp = "qsharp"
r = "r"
racket = "racket"
raku = "raku"
raml = "raml"
razor = "razor"
reason = "reason"
red = "red"
restructuredtext = "restructuredtext"
rexx = "rexx"
riot = "riot"
rmd = "rmd"
robot = "robotframework"
ruby = "ruby"
rust = "rust"
san = "san"
sbt = "sbt"
scala = "scala"
scilab = "scilab"
scss = "scss"
sdl = "sdlang"
shaderlab = "shaderlab"
shellscript = "shell"
silverstripe = "silverstripe"
slang = "slang"
slice = "slice"
slim = "slim"
smarty = "smarty"
snippets = "vscode"
snort = "snort"
solidity = "solidity"
sqf = "sqf"
sql = "sql"
squirrel = "squirrel"
stan = "stan"
stata = "stata"
stencil = "stencil"
stylable = "stylable"
stylus = "stylus"
svelte = "svelte"
swagger = "swagger"
swift = "swift"
swig = "swig"
systemverilog = "systemverilog"
t4 = "t4tt"
tera = "tera"
terraform = "terraform"
tex = "latex"
textile = "textile"
toml = "toml"
tt = "tt"
ttcn = "ttcn"
twig = "twig"
type = "vscode"
typescript = "typescript"
typescriptreact = "reactts"
typoscript = "typo3"
v = "vlang"
vb = "vb"
vba = "vba"
vbscript = "script"
velocity = "velocity"
verilog = "verilog"
vhdl = "vhdl"
viml = "vim"
volt = "volt"
vue = "vue"
wasm = "wasm"
wat = "wasm"
wenyan = "wenyan"
wolfram = "wolfram"
wurst = "wurst"
wurstlang = "wurst"
xmake = "xmake"
xml = "xml"
xquery = "xquery"
xsl = "xml"
yacc = "yacc"
yaml = "yaml"
yang = "yang"
zig = "zig"
