[audio]
types = [
    "aac",
    "act",
    "aiff",
    "amr",
    "ape",
    "au",
    "dct",
    "dss",
    "dvf",
    "flac",
    "gsm",
    "iklax",
    "ivs",
    "m4a",
    "m4b",
    "m4p",
    "mmf",
    "mogg",
    "mp3",
    "mpc",
    "msv",
    "oga",
    "ogg",
    "opus",
    "ra",
    "raw",
    "tta",
    "vox",
    "wav",
    "wma",
]

[video]
types = [
    "3g2",
    "3gp",
    "amv",
    "asf",
    "avi",
    "divx",
    "f4a",
    "f4b",
    "f4p",
    "f4v",
    "flv",
    "m2v",
    "m4v",
    "mk3d",
    "mkv",
    "mov",
    "mp2",
    "mp4",
    "mpe",
    "mpeg",
    "mpeg2",
    "mpg",
    "mpv",
    "nsv",
    "ogv",
    "qt",
    "rm",
    "rmvb",
    "svi",
    "vob",
    "webm",
    "wmv",
]

[image]
types = ["jpeg", "jpg", "gif", "png", "bmp", "tiff", "ico"]

[font]
types = ["woff", "woff2", "ttf", "otf", "eot", "pfa", "pfb", "sfd"]
